version: "3.8"

networks:
  prom_net:
    driver: bridge

services:
  sample_server_prom:
    build:
      context: ../
      dockerfile: config/sample_prom/Dockerfile
    container_name: sample_server_prom
    ports:
      - 3000:3000
    networks:
      - prom_net

  rest_api_server:
    build:
      context: ../
      dockerfile: config/rest_api/Dockerfile
    container_name: rest_api_server 
    ports:
      - 8080:8080
    networks:
      - prom_net

  mongodb:
    image: mongo
    container_name: api-mongodb
    depends_on:
      - rest_api_server
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=blessium
      - MONGO_INITDB_ROOT_PASSWORD=blessium

  prometheus_server:
    image: prom/prometheus:main
    container_name: prometheus_server
    depends_on: 
      - sample_server_prom
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - prom_net
